# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
#osx_image: xcode8
language: objective-c
# cache: cocoapods
podfile: Test-App/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
#- travis_wait 60 pod repo update > /dev/null 2>&1
#- travis_wait 60 ./pod-repo-update.sh
- travis_wait 60 pod repo update --silent
- pod install --project-directory=Test-App
#- cd Test-App && pod install && cd ..
script:
#- set -o pipefail && xcodebuild test -workspace Test-App/Sample.xcworkspace -scheme Sample -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild test -workspace Test-App/Sample.xcworkspace -scheme Sample -destination 'platform=iOS Simulator,name=iPhone 6' | xcpretty
#- pod lib lint
